<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Makefile Tab</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="..\..\style.css" rel="stylesheet" type="text/css"/>
</head>

<body>

<P><h3>Use custom Makefile</h3></P>
<blockquote>
<P>By default, Dev-C++ constructs its own makefile based on the configuration on the previous tabs. Here you can point Dev to a custom replacement. Dev-C++ will not generate any more makefiles if this option is used.</P>
</blockquote>

<P><h3>Information about customizing the makefile...</h3></P>
<blockquote>
<P>Click!</P>
</blockquote>

<P><h3>Include the following files into the makefile</h3></P>
<blockquote>
<P>If your custom makefile (or Dev's one) is getting so large that it can't be properly maintained in a single file anymore, you can then include files here.</P>
</blockquote>

</body></html>
